{% set name = "histolab" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/histolab-{{ version }}.tar.gz
  sha256: c0f6a6d0381f0ca056f524e3b8217b0a8304ea79a0cdc88f76a39b1bf7531031

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [win]

requirements:
  host:
    - pip
    - python
  run:
    - numpy >=1.18.4,<1.22.4
    - openslide-python
    - pillow >=8.4.0,<9.0.0
    - python
    - scikit-image >=0.19.0,<0.19.3
    - scipy >=1.5.0,<1.8.1
    - typing-extensions

test:
  imports:
    - histolab
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/histolab/histolab
  summary: Python library for Digital Pathology Image Processing
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ernestoarbitrio
