{% set name = "histolab" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/histolab-{{ version }}.tar.gz
  sha256: fcb8cf70fdf32a58e2980905d657ea53a541503a436e8303f0cb0da6e9f2e20f 

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  skip: True  # [win]

requirements:
  host:
    - pip
    - python
    - poetry
  run:
    - numpy >=1.18.4,<1.23.1
    - openslide-python <1.2.1
    - pillow >=9.1.0,<10.0.0
    - python
    - scikit-image >=0.19.0,<0.19.4
    - scipy >=1.5.0,<1.8.2
    - typing-extensions
    - importlib-metadata

test:
  imports:
    - histolab
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/histolab/histolab
  summary: Python library for Digital Pathology Image Processing
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ernestoarbitrio
